## SoundSpaces
NUM_PROCESSES: 9
EVAL_NUM_PROCESS: 1
NUM_UPDATES: 40000
LOG_INTERVAL: 10
LOG_FILE: "data/pointgoal/train.log"
CHECKPOINT_INTERVAL: 50
CHECKPOINT_FOLDER: "data/pointgoal/checkpoints"
EVAL_CKPT_PATH_DIR: "data/pointgoal/checkpoints/ckpt.96.pth"
# 96 98
TENSORBOARD_DIR: "data/pointgoal/tb"
TEST_EPISODE_COUNT: 500
SEED: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: []
# RL PPO
hidden_size: 512
ppo_epoch: 4
num_mini_batch: 1
num_steps: 150
value_loss_coef: 0.5
entropy_coef: 0.20
lr: 2.5e-4
eps: 1e-5
max_grad_norm: 0.5
use_linear_clip_decay: True
use_linear_lr_decay: True
clip_param: 0.1
reward_window_size: 50
use_gae: True
gamma: 0.99
tau: 0.95
min_std: 1e-6
max_std: 1
min_log_std: -5
max_log_std: 2
use_log_std: False
use_softplus: False
action_activation: tanh

## iGibson
scene: igibson
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: with_obj
trav_map_resolution: 0.1
trav_map_erosion: 3
should_open_all_doors: true

## Audio System
occl_multiplier: 1
spectrogram_window_len: 0.3
# task
task: point_nav_random
target_dist_min: 1.0
target_dist_max: 10.0
goal_format: polar
task_obs_dim: 4

# robot
robot:
    name: Turtlebot
    action_type: discrete
    action_normalize: true
    base_name: null
    scale: 1.0
    self_collision: false
    rendering_params: null
    controller_config:
        base:
            name: JointController
            motor_type: velocity
            command_input_limits: default
            command_output_limits: default
            use_delta_commands: false

# sensor spec
output: [task_obs, depth, audio, bump]
#task_obs, 
extra_rgb: false

# image
# ASUS Xtion PRO LIVE
# https://www.asus.com/us/3D-Sensor/Xtion_PRO_LIVE
fisheye: false
# image_width: 160
# image_height: 120
image_width: 128
image_height: 128
vertical_fov: 45
# depth
depth_low: 0.8
depth_high: 3.5
# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# audio
audio_dir: "/cvgl2/u/gdharan/clean_igibson/iGibson-dev/igibson/audio/telephone.wav"

# visual objects # not needed
visible_target: False

# reward only for point nav fixed task
reward_type: geodesic
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.005
time_reward_weight: -0.01

# termination condition
dist_tol: 0.36
# body width
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links
# discount factor
discount_factor: 0.99
# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

