# scene
scene: igibson
scene_id: Rs_int
urdf_file: /home/ziang/Workspace/Github/ig_dataset/scenes/Rs_int/urdf/Rs_int_task_re-shelving_library_books_simple_0_0_fixed_furniture
clutter: false
build_graph: true
load_texture: true
pybullet_load_texture: true
should_open_all_doors: false
load_object_categories: ["walls", "floors", "ceilings", "breakfast_table", "shelf", "hardback"]

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
robot:
  name: BehaviorRobot

  show_visual_head: False
  higher_limits: True  # This should probably be false.
  controller_config:
    gripper_right_hand:
      name: MultiFingerGripperController
      mode: ternary
    gripper_left_hand:
      name: MultiFingerGripperController
      mode: ternary

# task
task: re-shelving_library_books_simple
task_id: 0
instance_id: 0
online_sampling: false
should_highlight_task_relevant_objs: true

# discount factor
discount_factor: 0.99

# termination condition
max_step: 100

# sensor spec
output: [rgb]
# image
fisheye: false
image_width: 128
image_height: 128
vertical_fov: 120
# depth
depth_low: 0.0
depth_high: 10.0

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0
