# fetch_rl_cleaning_microwave_oven
# scene
# Task List:
# scene_id | task | task_id | instance_id | max length | time penalty
# Beechwood_0_int | installing_a_printer | 0 | 2 | 20 | 0.1
# Pomaria_1_int | throwing_away_leftovers | 0 | 2 | 40 | 0.01
scene: igibson
scene_id: Benevolence_1_int  # Pomaria_1_int  # Beechwood_0_int
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: no_obj
trav_map_resolution: 0.1
trav_map_erosion: 3
should_open_all_doors: true

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
robot:
  name: Fetch
  action_type: continuous
  action_normalize: false
  base_name: null
  scale: 1.0
  self_collision: true
  rendering_params: null
  grasping_mode: assisted
  rigid_trunk: false
  default_trunk_offset: 0.365
  default_arm_pose: diagonal30
  controller_config:
    base:
      name: DifferentialDriveController
    arm_0:
      name: JointController
      use_delta_commands: False
      motor_type: position
      command_input_limits: null
      command_output_limits: null
    gripper_0:
      name: MultiFingerGripperController
      mode: binary
    camera:
      name: JointController
      use_delta_commands: False

# task
#task: room_rearrangement

task: cleaning_microwave_oven  # putting_leftovers_away  # putting_away_toys # throwing_away_leftovers  # installing_a_printer
task_id: 0
instance_id: 0  # 0
online_sampling: false
should_highlight_task_relevant_objs: false

#load_object_categories: [
#  bottom_cabinet,
#  bottom_cabinet_no_top,
#  top_cabinet,
#  dishwasher,
#  fridge,
#  microwave,
#  oven,
#  washer
#  dryer,
#]

# reward
potential_reward_weight: 1.0
prismatic_joint_reward_scale: 3.0
revolute_joint_reward_scale: 1.0

# discount factor
discount_factor: 0.99

# termination condition
max_step: 40
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [0, 1, 2]  # ignore collisions with these robot links

# sensor spec
output: [ins_seg, occupancy_grid]  # [rgb, occupancy_grid]  # , depth, occupancy_grid] # scan,
# image
# Primesense Carmine 1.09 short-range RGBD sensor
# http://xtionprolive.com/primesense-carmine-1.09
fisheye: false
image_width: 512
image_height: 512
vertical_fov: 90
# depth
depth_low: 0.35
depth_high: 3.0
# scan
# SICK TIM571 scanning range finder
# https://docs.fetchrobotics.com/robot_hardware.html
# n_horizontal_rays is originally 661, sub-sampled 1/3
n_horizontal_rays: 220
n_vertical_beams: 1
laser_linear_range: 25.0
laser_angular_range: 220.0
min_laser_dist: 0.05
laser_link_name: laser_link

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visible_target: true
visible_path: false