            
scene: igibson
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: with_obj
trav_map_resolution: 0.1
trav_map_erosion: 3
should_open_all_doors: true

# task
task: point_nav_random
target_dist_min: 1.0
target_dist_max: 5.0
goal_format: cartesian
task_obs_dim: 4

# robot
robot:
   name: Turtlebot
   action_type: discrete
   action_normalize: true
   base_name: null
   scale: 1.0
   self_collision: false
   rendering_params: null
   controller_config:
     base:
       name: DifferentialDriveController

# sensor spec
output: [depth, audio]
extra_rgb: false
audio_write: ""

# image
fisheye: false
image_width: 160
image_height: 160
vertical_fov: 45
# depth
depth_low: 0.8
depth_high: 3.5
# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# reward only for point nav fixed task
reward_type: geodesic
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.005
time_reward_weight: -0.01

# termination condition
dist_tol: 0.36
# body width
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links
# discount factor
discount_factor: 0.99
# domain randomization
texture_randomization_freq: null
object_randomization_freq: null














