assets_path: data/rt_assets # OTS default is: data/assets # put either absolute path or relative to current directory
g_dataset_path: data/rt_dataset # OTS default is: data/g_dataset
ig_dataset_path: data/rt_dataset # OTS default is: data/ig_dataset
threedfront_dataset_path: data/threedfront_dataset
cubicasa_dataset_path: data/cubicasa_dataset
