scene: building
model_id: area1
action_timestep: 0.25
actor_fc_layers: [256]
actor_learning_rate: 0.0003
additional_states_dim: 2
alpha_learning_rate: 0.0003
automatic_reset: true
batch_size: 256
collect_steps_per_iteration: 1
collision_ignore_body_b_ids: [0, 1, 2]
collision_ignore_link_a_ids: []
collision_reward_weight: -1.0
connectivity:
  c-mid: [c1-ped, c2-ped, c3-ped, c4-ped]
  c1-ped: [c-mid]
  c1-rob: [c2-rob, c3-rob, c4-rob]
  c2-ped: [c-mid]
  c2-rob: [c1-rob, c3-rob, c4-rob]
  c3-ped: [c-mid]
  c3-rob: [c1-rob, c2-rob, c4-rob]
  c4-ped: [c-mid]
  c4-rob: [c1-rob, c2-rob, c3-rob]
  d1-ped: [d2-ped]
  d1-rob: [d2-rob, d4-rob, d5-rob, d6-rob]
  d2-ped: [d1-ped, d4-ped, d5-ped, d6-ped]
  d2-rob: [d1-rob, d4-rob, d6-rob, d5-rob]
  d3-ped: [d4-ped]
  d3-rob: [d4-rob, d2-rob, d5-rob, d6-rob]
  d4-ped: [d3-ped, d2-ped, d6-ped, d5-ped]
  d4-rob: [d3-rob, d2-rob, d5-rob, d6-rob]
  d5-ped: [d2-ped, d4-ped, d6-ped]
  d5-rob: [d1-rob, d2-rob, d3-rob, d4-rob, d6-rob]
  d6-ped: [d2-ped, d4-ped, d5-ped]
  d6-rob: [d1-rob, d2-rob, d3-rob, d4-rob, d5-rob]
  h1-ped: [h2-ped]
  h1-rob: [h2-rob]
  h2-ped: [h1-ped]
  h2-rob: [h1-rob]
  ped-waypoints: [c1-mid, d2-ped, d4-ped]
conv_1d_layer_params:
- [32, 8, 4]
- [64, 4, 2]
- [64, 3, 1]
conv_2d_layer_params:
- - 32
  - [8, 8]
  - 4
- - 64
  - [4, 4]
  - 2
- - 64
  - [3, 3]
  - 1
critic_action_fc_layers: [256]
critic_joint_fc_layers: [256]
critic_learning_rate: 0.0003
critic_obs_fc_layers: [256]
crowdnav_circle_radius: 4
crowdnav_square_width: 10
debug: false
display_ui: false
dist_tol: 0.5
electricity_reward_weight: 0.0
encoder_fc_layers: [256]
env_type: gibson
eval_interval: 20000
fast_lq_render: true
fov: 90
gamma: 0.99
gpu_g: 0
initial_collect_steps: 1000
is_discrete: false
locations:
  c-mid: {center_x: 0.0, center_y: 10.0, x_range_radius: 0.5, y_range_radius: 0.5}
  c1-ped: {center_x: -6.5, center_y: 10.5, x_range_radius: 3.0, y_range_radius: 0.5}
  c1-rob: {center_x: -6.5, center_y: 10.5, x_range_radius: 3.0, y_range_radius: 0.5}
  c2-ped: {center_x: 0.0, center_y: 4.5, x_range_radius: 0.5, y_range_radius: 3.0}
  c2-rob: {center_x: 0.0, center_y: 4.5, x_range_radius: 0.5, y_range_radius: 3.0}
  c3-ped: {center_x: 6.5, center_y: 10.5, x_range_radius: 3.0, y_range_radius: 0.5}
  c3-rob: {center_x: 6.5, center_y: 10.5, x_range_radius: 3.0, y_range_radius: 0.5}
  c4-ped: {center_x: 0.0, center_y: 15.5, x_range_radius: 0.5, y_range_radius: 3.0}
  c4-rob: {center_x: 0.0, center_y: 15.5, x_range_radius: 0.5, y_range_radius: 3.0}
  d1-ped: {center_x: -6.0, center_y: 16.0, x_range_radius: 1.0, y_range_radius: 1.0}
  d1-rob: {center_x: -6.0, center_y: 16.0, x_range_radius: 1.0, y_range_radius: 1.0}
  d2-ped: {center_x: -6.0, center_y: 23.5, x_range_radius: 0.1, y_range_radius: 0.1}
  d2-rob: {center_x: -6.0, center_y: 23.5, x_range_radius: 3.0, y_range_radius: 0.1}
  d3-ped: {center_x: 6.0, center_y: 16.0, x_range_radius: 1.0, y_range_radius: 1.0}
  d3-rob: {center_x: 6.0, center_y: 16.0, x_range_radius: 1.0, y_range_radius: 1.0}
  d4-ped: {center_x: 6.0, center_y: 23.5, x_range_radius: 0.1, y_range_radius: 0.1}
  d4-rob: {center_x: 6.0, center_y: 23.5, x_range_radius: 3.0, y_range_radius: 0.1}
  d5-ped: {center_x: -14.0, center_y: 23.5, x_range_radius: 3.0, y_range_radius: 0.1}
  d5-rob: {center_x: -14.0, center_y: 23.5, x_range_radius: 3.0, y_range_radius: 0.1}
  d6-ped: {center_x: 14.0, center_y: 23.5, x_range_radius: 3.0, y_range_radius: 0.1}
  d6-rob: {center_x: 14.0, center_y: 23.5, x_range_radius: 3.0, y_range_radius: 0.1}
  h1-ped: {center_x: 6.5, center_y: -10.0, x_range_radius: 3.0, y_range_radius: 0.5}
  h1-rob: {center_x: 6.5, center_y: -10.0, x_range_radius: 3.0, y_range_radius: 0.5}
  h2-ped: {center_x: -6.5, center_y: -10.0, x_range_radius: 3.0, y_range_radius: 0.5}
  h2-rob: {center_x: -6.5, center_y: -10.0, x_range_radius: 3.0, y_range_radius: 0.5}
max_angular_velocity: 0.7853981633974483
max_linear_velocity: 1.0
max_step: 200
mode: headless
movements:
  agent:
    sources: [h1-rob, h2-rob]
    sources_per_location:
      crossing: [c1-rob, c2-rob, c3-rob, c4-rob]
      doorway: [d1-rob, d2-rob, d3-rob, d4-rob, d5-rob, d6-rob]
      hallway: [h1-rob, h2-rob]
  pedestrians:
    crossing:
      sources: [c1-ped, c2-ped, c3-ped, c4-ped]
    doorway:
      sources: [d1-ped, d3-ped, d5-ped, d6-ped]
    flip_prob: 0.5
    hallway:
      sources: [h1-ped, h2-ped]
n_horizontal_rays: 128
n_vertical_beams: 1
num_eval_episodes: 10
num_iterations: 125000
num_obstacles: 0
num_parallel_environments: 8
num_parallel_environments_eval: 1
num_pedestrians: {crossing: 0, crowdnav_circle_crossing: 0, crowdnav_square_crossing: 0,
  doorway: 0, hallway: 0}
pedestrians_can_see_robot: false
pedestrians_dynamics: {chat_distance_max: 0, chat_distance_min: 0, chat_interval_max: 0,
  chat_interval_min: 0, chat_min_delay: 0, chat_probability: 0, dist_tol: 1.0, kinematics: holonomic,
  max_angular_velocity: 1.0, max_linear_velocity: 1.0, max_pause_interval: 0, min_pause_interval: 0,
  min_separation: 0.3, personal_space: 0.2, policy: orca, position_noise: 0.0, radius: 0.3,
  sensor: coordinates, use_pedestrian_behaviors: false, v_pref: 1.0, velocity_noise: 0.0,
  visible: true}
physics_timestep: 0.25
potential_reward_weight: 1.0
psv_reward_weight: 0.0
randomize_pedestrian_attributes: false
render_to_tensor: true
replay_buffer_capacity: 150000
resolution: 512
reward_type: l2
robot: JR2
robot_pedestrians_min_separation: 2.0
robot_to_scan_config: configs/robot_to_scan.yaml
root_dir: experiments/jr2_hallway_0_peds
scan_mode: xyz
scene: stadium
sensor_inputs: [sensor, scan]
show_diagnostics: false
slack_reward: -0.001
stall_torque_reward_weight: 0.0
success_reward: 1.0
target_update_period: 1
target_update_tau: 0.005
target_visible_to_agent: false
task: pointgoal
train_steps_per_iteration: 1
use_crowdnav_scenario: false
use_filler: true
verbose: false
visualize_initial: true
visualize_lidar: true
visualize_target: true
visualize_waypoints: true
walls:
  walls_dim:
  - [10.0, 0.5, 1.0]
  - [10.0, 0.5, 1.0]
  - [0.5, 21.0, 1.0]
  - [0.5, 21.0, 1.0]
  - [4.5, 0.5, 1.0]
  - [4.5, 0.5, 1.0]
  - [4.5, 0.5, 1.0]
  - [4.5, 0.5, 1.0]
  - [0.5, 4.5, 1.0]
  - [0.5, 4.5, 1.0]
  - [0.5, 4.5, 1.0]
  - [0.5, 4.5, 1.0]
  - [5.5, 0.5, 1.0]
  - [5.5, 0.5, 1.0]
  - [5.5, 0.5, 1.0]
  - [5.5, 0.5, 1.0]
  - [17.5, 0.5, 1.0]
  - [0.5, 5.0, 1.0]
  - [0.5, 5.0, 1.0]
  walls_pos:
  - [0, -11.5, 0.6]
  - [0, -8.5, 0.6]
  - [10.5, 0.5, 0.6]
  - [-10.5, 0.5, 0.6]
  - [-5.5, 9, 0.6]
  - [-5.5, 12, 0.6]
  - [5.5, 9, 0.6]
  - [5.5, 12, 0.6]
  - [1.5, 17, 0.6]
  - [-1.5, 17, 0.6]
  - [1.5, 4.0, 0.6]
  - [-1.5, 4.0, 0.6]
  - [0.0, -1.0, 0.6]
  - [0.0, 22, 0.6]
  - [-12.5, 22.0, 0.6]
  - [12.5, 22.0, 0.6]
  - [0.0, 25.0, 0.6]
  - [-18, 20.5, 0.6]
  - [18, 20.5, 0.6]
waypoint_resolution: 0.5
waypoints: 6
