envname: HuskyNavigateEnv
model_id: sRj553CTHiw
target_orn: [0, 0, 1.57]
target_pos: [-14.3, 45.07, 0.5]
initial_orn: [0, 0, 4.71]
initial_pos: [-14.3, 5, 1.2]
fov: 1.57
use_filler: true
views: []
display_ui: true
show_dignostic: true
ui_num: 2