# scene
# scene: stadium_obstacle
# scene: stadium_congested # remember to change target_pos
#scene: stadium_difficult # remember to change target_pos
scene: stadium
# scene: building
# model_id: Ohoopee

num_obstacles: 0
num_pedestrians: 5
pedestrians_can_see_robot: false

# robot
robot: Turtlebot
velocity: 0.1

# task, observation and action
task: pointgoal # pointgoal|objectgoal|areagoal|reaching

initial_pos: [-2.0, 2.0, 0.0]
initial_orn: [0.0, 0.0, 0.0]

target_pos: [-2.0, 2.0, 0.0]
target_orn: [0.0, 0.0, 0.0]

is_discrete: false
additional_states_dim: 3

# reward
success_reward: 1.0
slack_reward: -0.001
potential_reward_weight: 1.0
#electricity_reward_weight: -0.02
#stall_torque_reward_weight: -0.0001
electricity_reward_weight: 0.0
stall_torque_reward_weight: 0.0
collision_reward_weight: -1.0

# termination condition
dist_tol: 0.5
max_step: 300

# sensor
# output: [sensor, rgb, depth]
# output: [sensor, scan, pedestrian]
#output: [sensor, pedestrian]
# output: [sensor, scan]
output: [sensor, depth, pedestrian_position, pedestrian_velocity]
scan_beams: 512 #128 
scan_vertical_beams: 1 #9 
resolution: 64
#waypoints: 5
fov: 90

# display
use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

speed:
  timestep: 0.001
  frameskip: 10

mode: headless #gui|web_ui
verbose: false
fast_lq_render: true

# visual objects
visual_object_at_initial_pos: false
visual_object_at_target_pos: true
target_visual_object_visible_to_agent: true

# debug
debug: false
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: true

humans:
  visible: true
  policy: orca
  radius: 0.3
  v_pref: 1.0
  position_noise: 0.0
  velocity_noise: 0.0
  sensor: coordinates
  personal_space: 1.0
  max_linear_velocity: 1.0
  max_angular_velocity: 1.0
  kinematics: holonomic
  # for random initialization and goal setting
  initial_position:
     min_x: -5.0
     max_x: 5.0
     min_y: -5.0
     max_y: 5.0
  target_position:
     min_x: -5.0
     max_x: 5.0
     min_y: -5.0
     max_y: 5.0
     


