# scene
# scene: stadium_obstacle
# scene: stadium_congested # remember to change target_pos
#scene: stadium_difficult # remember to change target_pos
scene: stadium
# scene: building
# model_id: Ohoopee

has_pedestrians: true
pedestrian_can_see_robot: false
num_pedestrians: 3

# robot
robot: Turtlebot
velocity: 0.5

# task, observation and action
task: pointgoal # pointgoal|objectgoal|areagoal|reaching

#initial_orn: [0.0, 0.0, 0.0]
#initial_pos: [6.0, 1.0, 0.0] # stadium_congested/ stadium_obstacle: [6.0, -6.0, 0.0]  # Ohoopee: [0.0, 0.0, 0.0]
# stadium_difficult: [6.0, 1.0, 0.0]

#target_orn: [0.0, 0.0, 0.0]
#target_pos: [4.0, 3.0, 0.0] # stadium_congested: [2.0, -2.0, 0.0] # stadium_obstacle: [-3., 4., 0.] # Ohoopee: [-4.4, 2.7, 0.0]
# stadium_difficult: [4.0, 3.0, 0.0]

initial_pos: [-3.0, 3.0, 0.0]
initial_orn: [0.0, 0.0, 0.0]

target_pos: [-3.0, 3.0, 0.0]
target_orn: [0.0, 0.0, 0.0]

is_discrete: false
additional_states_dim: 3

# reward
terminal_reward: 5000
#electricity_cost: -0.02
#stall_torque_cost: -0.0001
electricity_cost: 0.0
stall_torque_cost: 0.0
discount_factor: 0.99
collision_reward_weight: 1.0
potential_reward_weight: 20.0

# termination condition
dist_tol: 0.1
max_step: 400

# sensor
# output: [sensor, rgb, depth]
# output: [sensor, scan, pedestrian]
output: [sensor, depth, pedestrian]
# output: [sensor, scan]
scan_beams: 512 #128 
scan_vertical_beams: 1 #9 
resolution: 64
waypoints: 5
fov: 90

# display
use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

speed:
  timestep: 0.001
  frameskip: 10

mode: headless #gui|web_ui
verbose: false
fast_lq_render: true

# visual objects
visual_object_at_initial_pos: false
visual_object_at_target_pos: true
target_visual_object_visible_to_agent: true

# debug
debug: false
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: true
