# scene
#scene: stadium
scene: building
model_id: Ohoopee

# robot
robot: Turtlebot
velocity: 0.1

# task, observation and action
task: pointgoal # pointgoal|objectgoal|areagoal|reaching

#initial_pos_low: [-9.0, -0.5, 0.0]
#initial_pos_high: [1.0, 4.5, 0.0]
#initial_orn_low: [0.0, 0.0, 0.0]
#initial_orn_high: [0.0, 0.0, 6.283185307179586]
#
#target_pos_low: [-9.0, -0.5, 0.0]
#target_pos_high: [1.0, 4.5, 0.0]
#target_orn_low: [0.0, 0.0, 0.0]
#target_orn_high: [0.0, 0.0, 6.283185307179586]

valid_pos: [[-9.0, 3.0, 0.0],
            [-9.0, 4.0, 0.0],
            [-8.0, -0.5, 0.0],
            [-8.0, 3.0, 0.0],
            [-8.0, 4.0, 0.0],
            [-7.0, 3.0, 0.0],
            [-6.0, 1.0, 0.0],
            [-6.25, 2.0, 0.0],
            [-6.25, 3.0, 0.0],
            [-5.0, -1.0, 0.0],
            [-5.0, 0.0, 0.0],
            [-5.0, 1.0, 0.0],
            [-5.0, 2.0, 0.0],
            [-5.0, 3.0, 0.0],
            [-4.0, -1.0, 0.0],
            [-4.0, 3.0, 0.0],
            [-3.0, -1.0, 0.0],
            [-3.0, 3.0, 0.0],
            [-2.5, 0.0, 0.0],
            [-2.5, 1.0, 0.0],
            [-2.5, 2.0, 0.0],
            [-1.0, 0.0, 0.0],
            [-1.0, 3.0, 0.0],
            [-1.0, 4.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 2.0, 0.0],
            [1.0, 2.5, 0.0],
            [2.0, 2.5, 0.0]]

#initial_pos_low: [0.0, 0.0, 0.0]
#initial_pos_high: [0.0, 0.0, 0.0]
#initial_orn_low: [0.0, 0.0, 0.0]
#initial_orn_high: [0.0, 0.0, 0.0]
#
#target_pos_low: [3.0, 3.0, 0.0]
#target_pos_high: [3.0, 3.0, 0.0]
#target_orn_low: [0.0, 0.0, 0.0]
#target_orn_high: [0.0, 0.0, 0.0]

initial_pos_low: [-5.0, -5.0, 0.0]
initial_pos_high: [5.0, 5.0, 0.0]
initial_orn_low: [0.0, 0.0, 0.0]
initial_orn_high: [0.0, 0.0, 6.283185307179586]

target_pos_low: [-5.0, -5.0, 0.0]
target_pos_high: [5.0, 5.0, 0.0]
target_orn_low: [0.0, 0.0, 0.0]
target_orn_high: [0.0, 0.0, 6.283185307179586]


is_discrete: true
additional_states_dim: 3

# reward
terminal_reward: 5000
#electricity_cost: -0.02
#stall_torque_cost: -0.0001
electricity_cost: 0.0
stall_torque_cost: 0.0
discount_factor: 0.99

# termination condition
dist_tol: 0.5
max_step: 500

# sensor
output: [sensor, rgb, depth]
resolution: 64
fov: 1.57

# display
use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose: false
  random_target_pose: false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

speed:
  timestep: 0.001
  frameskip: 10

mode: web_ui #gui|headless
verbose: false
fast_lq_render: true

# visual objects
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: true
